### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by AugustKRZhu** [corpnewt/OC-Update#2]
Hi, I downloaded it and run the command and got the outputs.

....Checking schema mAcpiAddSchemaEntry
Checking schema mAcpiAddSchema
Checking schema mAcpiDeleteSchemaEntry
Checking schema mAcpiDeleteSchema
Checking schema mAcpiPatchSchemaEntry
Checking schema mAcpiPatchSchema
Checking schema mAcpiQuirksSchema
Checking schema mAcpiConfigurationSchema
Checking schema mBooterWhitelistEntrySchema
Checking schema mBooterWhitelistSchema
Checking schema mBooterQuirksSchema
Checking schema mBooterPatchSchemaEntry
Checking schema mBooterPatchSchema
Checking schema mBooterConfigurationSchema
Checking schema mDevicePropertiesAddEntrySchema
Checking schema mDevicePropertiesAddSchema
Checking schema mDevicePropertiesDeleteEntrySchema
Checking schema mDevicePropertiesDeleteSchema
Checking schema mDevicePropertiesSchema
Checking schema mKernelAddSchemaEntry
Checking schema mKernelAddSchema
Checking schema mKernelBlockSchemaEntry
Checking schema mKernelBlockSchema
Checking schema mKernelEmulateSchema
Checking schema mKernelForceSchemaEntry
Checking schema mKernelForceSchema
Checking schema mKernelPatchSchemaEntry
Checking schema mKernelPatchSchema
Checking schema mKernelQuirksSchema
Checking schema mKernelSchemeSchema
Checking schema mKernelConfigurationSchema
Checking schema mMiscBlessOverrideSchema
Checking schema mMiscConfigurationBootSchema
Checking schema mMiscConfigurationDebugSchema
Checking schema mMiscConfigurationSecuritySchema
Checking schema mMiscEntriesSchemaEntry
Checking schema mMiscEntriesSchema
Checking schema mMiscToolsSchemaEntry
Checking schema mMiscToolsSchema
Checking schema mMiscConfigurationSchema
Checking schema mNvramAddEntrySchema
Checking schema mNvramAddSchema
Checking schema mNvramDeleteEntrySchema
Checking schema mNvramDeleteSchema
Checking schema mNvramLegacyEntrySchema
Checking schema mNvramLegacySchema
Checking schema mNvramConfigurationSchema
Checking schema mPlatformConfigurationDataHubSchema
Checking schema mPlatformConfigurationGenericSchema
Checking schema mPlatformConfigurationMemoryDeviceEntry
Checking schema mPlatformConfigurationMemoryDevicesSchema
Checking schema mPlatformConfigurationMemorySchema
Checking schema mPlatformConfigurationNvramSchema
Checking schema mPlatformConfigurationSmbiosSchema
Checking schema mPlatformConfigurationSchema
Checking schema mUefiDriversSchema
Checking schema mUefiQuirksSchema
Checking schema mUefiProtocolOverridesSchema
Checking schema mUefiApfsSchema
Checking schema mUefiAppleInputSchema
Checking schema mUefiAudioSchema
Checking schema mUefiInputSchema
Checking schema mUefiOutputSchema
Checking schema mUefiReservedMemoryEntrySchema
Checking schema mUefiReservedMemorySchema
Checking schema mUefiConfigurationSchema
Checking schema mRootConfigurationNodes
Cloning https://github.com/acidanthera/OcBinaryData...
Cloning into 'OcBinaryData'...
remote: Enumerating objects: 1139, done.
remote: Counting objects: 100% (482/482), done.
remote: Compressing objects: 100% (461/461), done.
remote: Total 1139 (delta 55), reused 87 (delta 20), pack-reused 657
Receiving objects: 100% (1139/1139), 67.52 MiB | 3.30 MiB/s, done.
Resolving deltas: 100% (127/127), done.
Copying HfsPlusLegacy.efi to OC...
Copying HfsPlus.efi to OC...
Copying HfsPlus32.efi to OC...
Copying ExFatDxe.efi to OC...
Copying ExFatDxeLegacy.efi to OC...
Copying ControlMsrE2.efi to OC...
Copying TpmInfo.efi to OC...
Copying PropertyTest.efi to OC...
Copying OpenRuntime.efi to OC...
Copying NvmExpressDxe.efi to OC...
Copying BootKicker.efi to OC...
Copying GopStop.efi to OC...
Copying OpenUsbKbDxe.efi to OC...
Copying CryptoTest.efi to OC...
Copying PavpProvision.efi to OC...
Copying OpenCanopy.efi to OC...
Copying SmbiosTest.efi to OC...
Copying RtcRw.efi to OC...
Copying ChipTune.efi to OC...
Copying VerifyMemOpt.efi to OC...
Copying KeyTester.efi to OC...
Copying CrScreenshotDxe.efi to OC...
Copying MmapDump.efi to OC...
Copying OpenControl.efi to OC...
Copying OpenPartitionDxe.efi to OC...
Copying DataHubTestApp.efi to OC...
Copying DataHubTest.efi to OC...
Copying SmbiosTestApp.efi to OC...
Copying HiiDatabase.efi to OC...
Copying CleanNvram.efi to OC...
Copying AcpiTestApp.efi to OC...
Copying CryptoTestApp.efi to OC...
Copying CsrUtil.efi to OC...
Copying Shell.efi to OC...
Copying ResetSystem.efi to OC...
Copying Ps2MouseDxe.efi to OC...
Copying AcpiTest.efi to OC...
Copying OpenCore.efi to OC...
Copying GopPerf.efi to OC...
Copying GdbSyms.efi to OC...
Copying PropertyTestApp.efi to OC...
Copying XhciDxe.efi to OC...
Copying Bootstrap.efi to OC...
Copying Ps2KeyboardDxe.efi to OC...
Copying OpenHfsPlus.efi to OC...
Copying AudioDxe.efi to OC...
Copying UsbMouseDxe.efi to OC...
Copying SampleCustom.plist to OC...
Copying Sample.plist to OC...
Copying Configuration.pdf to OC...
Copying Differences.pdf to OC...
Copying OcBinaryData/Resources to OC folder...
Done.

[Process completed]

after that, I need to use the generated OC to replace the ./EFI/OC ? or how can I do?

Best.

**Comment by corpnewt** [comment]
If it did not update your booted EFI for you, then I'm guessing your `ExposeSensitiveData` value in your config.plist does not is lacking the `0x01` bit to expose the booter path as the script currently uses the following to attempt to obtain that:

```sh
target_disk="$(nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:boot-path | sed 's/.*GPT,\([^,]*\),.*/\1/')"
```

Alternatively - you can manually point it to a disk/mount point with the `-d DISK, --disk DISK` option.

The output you've pasted above shows that it did clone and build the repo - and copied everything to the local OC folder, it just doesn't appear to know where to copy the resulting files.

-CorpNewt
